export const BRANDS = [
  'Herbal Tide',
  'Imperia',
  'AiV Pure Extracts',
  'Alchemist Cupboard- CA',
  'American Spice',
  'Americn E-Juice',
  'Atmos Labs',
  'Azure Vaping',
  'Baker Flavors',
  'Baker Flavors (VZ origins)',
  'Bakers Flavors',
  'Bakto Naturals',
  'Best Flavors',
  'Bickford',
  'Bolsjehuset',
  'CA- FA- FW- TFA-INW-++',
  'CA- FW',
  'CA- FW- FA- INW- TFA-LA',
  'CA- INW- Salub Arome-FW',
  'CA-FW-TFA-Flav.Fantasy',
  'CA-OoO-TFA-TP-INW-FA-FW',
  'Capella (CA)',
  'Chefs Flavoring UK',
  'Chinese Tobacco Blends',
  'Cooks Flavor Extracts',
  'Crave Gourmet',
  'DarkStar-TFA- FW- CA',
  'Decadent Vapours (DV)',
  'Delosi',
  'DIY Flavor Shack',
  'Essence Flavor Concentrates',
  'Essence- LA- CA',
  'Euro Flavor',
  'FA- CA-',
  'FA- TFA- CA- Essence',
  'Faeries Finest ',
  'Faeries Finest (FF)',
  'FA-FW- LA- TFA- FF- CA',
  'Fantes Flavors',
  'Flavor Apprentice (TFA/TPA)',
  'Flavor Art (FA)',
  'Flavor Concentrates',
  'Flavor West (FW)',
  'Flavorah',
  'Flavorah ',
  'FlavorConcentrates',
  'Flavors Express',
  'Frontier',
  'FW- NF- TFA- CA',
  'German Flavors',
  'Get Suckered',
  'Gremlin Juice',
  'Hangsen',
  'Health Cabin (HC)',
  'HiLiq',
  'IDE (Mother Murphys)',
  'Inawera',
  'Inawera (INW)',
  'Juicy Liquid',
  'Jungle Flavors',
  'LA- CK- Silver Cloud',
  'LA-CA-TFA-INW-Seedman-WF-FA',
  'Liquid Barn',
  'LorAnn (LA)',
  'Lotus (Medicine Flower)',
  'Marsden & Bathe',
  'Medicine Flower',
  'Medicine Flower Dilutions',
  'Medicine Flower Organic',
  'Meiwei- Atmos- FA- CA- TFA',
  'Molinberry Flavors',
  'Mom & Pop',
  'Mt. Baker',
  'MyVapeJuice',
  'Natures Flavors (NF)',
  'Nicotine Labs',
  'NicVape',
  'Northwest VG',
  'Nude Nicotine',
  'Olive Nation',
  'One on One',
  'One Stop Blends',
  'One Stop Flavors',
  'Purilum',
  'Rainforest Flavors',
  'Real Flavors',
  'Real Flavors (AKA Northwest)',
  'Real Flavors VG',
  'Savory Spice Shop',
  'Signature (TFA)',
  'Silver Cloud',
  'Spice Barn',
  'Spices Etc Natural Flavors',
  'Steam Spirit Flavors',
  'Super Concentrated',
  'Superior Flavoring',
  'Suttons Bay',
  'Taste Flavors',
  'Tasty Puff (TP)',
  'TFA',
  'TFA/HV (Heartland)/FW/CA',
  'TFA/TPA',
  'Vaping Zone (VZ)',
  'Vapor Renew- FW',
  'Vapor Shots (VS)',
  'Viper Flavor',
  'Vista',
  'Want2Vape Concentrates',
  'Wonder Flavours',
  'Zibelli',
]
