export const FETCH_FLAVORS = "FETCH_FLAVORS";
export const FETCH_SINGLE_FLAVOR = "FETCH_SINGLE_FLAVOR";
export const ADD_FLAVOR = "ADD_FLAVOR";
export const DELETE_FLAVOR = "DELETE_FLAVOR";
export const UPDATE_FLAVOR = "UPDATE_FLAVOR";
export const CLEAN_SELECTED_FLAVOR = "CLEAN_SELECTED_FLAVOR";
export const UPDATE_FLAVOR_FIELD = "UPDATE_FLAVOR_FIELD";

export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_PUBLIC_RECIPES = "FETCH_PUBLIC_RECIPES";
export const FETCH_SINGLE_RECIPE = "FETCH_SINGLE_RECIPE";
export const ADD_RECIPE = "ADD_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const CLEAN_SELECTED_RECIPE = "CLEAN_SELECTED_RECIPE";
export const UPDATE_RECIPE_FIELD = "UPDATE_RECIPE_FIELD";
export const ADD_FLAVOR_TO_RECIPE = "ADD_FLAVOR_TO_RECIPE";
export const EDIT_FLAVOR_TO_RECIPE = "EDIT_FLAVOR_TO_RECIPE";
export const DELETE_FLAVOR_TO_RECIPE = "DELETE_FLAVOR_TO_RECIPE";
export const UPDATE_RECIPE_WITH_PRODUCTION = "UPDATE_RECIPE_WITH_PRODUCTION";

//user
export const FETCH_USER = "FETCH_USER";

//reviews
export const FETCH_REVIEWS = "FETCH_REVIEWS";
export const ADD_REVIEW = "ADD_REVIEW";

//toggle bvetween dark and light theme
export const TOGGLE_THEME = "TOGGLE_THEME";

// search
export const SEARCH_FLAVOR = "SEARCH_FLAVOR";
export const SEARCH_RECIPE = "SEARCH_RECIPE";

//steep
export const UPDATE_TIMER_FIELD = "UPDATE_TIMER_FIELD";
export const UPDATE_STEP_FIELD = "UPDATE_STEP_FIELD";
export const ADD_STEP_TO_TIMER = "ADD_STEP_TO_TIMER";
export const CLEAN_SELECTED_TIMER = "CLEAN_SELECTED_TIMER";
export const CLEAN_SELECTED_STEP = "CLEAN_SELECTED_STEP";
export const ADD_TIMER = "ADD_TIMER";

export const FETCH_TIMERS = "FETCH_TIMERS";
export const FETCH_SINGLE_RECIPE_TIMER = "FETCH_SINGLE_RECIPE_TIMER";
