export const FETCH_FLAVORS = "FETCH_FLAVORS";
export const FETCH_SINGLE_FLAVOR = "FETCH_SINGLE_FLAVOR";
export const ADD_FLAVOR = "ADD_FLAVOR";
export const DELETE_FLAVOR = "DELETE_FLAVOR";
export const UPDATE_FLAVOR = "UPDATE_FLAVOR";
export const CLEAN_SELECTED_FLAVOR = "CLEAN_SELECTED_FLAVOR";
export const UPDATE_FLAVOR_FIELD = "UPDATE_FLAVOR_FIELD";

export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_PUBLIC_RECIPES = "FETCH_PUBLIC_RECIPES";
export const FETCH_SINGLE_RECIPE = "FETCH_SINGLE_RECIPE";
export const ADD_RECIPE = "ADD_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const CLEAN_SELECTED_RECIPE = "CLEAN_SELECTED_RECIPE";
export const UPDATE_RECIPE_FIELD = "UPDATE_RECIPE_FIELD";
export const ADD_FLAVOR_TO_RECIPE = "ADD_FLAVOR_TO_RECIPE";
export const EDIT_FLAVOR_TO_RECIPE = "EDIT_FLAVOR_TO_RECIPE";
export const DELETE_FLAVOR_TO_RECIPE = "DELETE_FLAVOR_TO_RECIPE";
export const UPDATE_RECIPE_WITH_PRODUCTION = "UPDATE_RECIPE_WITH_PRODUCTION";
// export const FILTER_RECIPES_BY_FLAVOR = 'FILTER_RECIPES_BY_FLAVOR'

export const FETCH_USER = "FETCH_USER";

export const FETCH_REVIEWS = "FETCH_REVIEWS";
export const ADD_REVIEW = "ADD_REVIEW";

export const TOGGLE_THEME = "TOGGLE_THEME";

export const SEARCH_FLAVOR = "SEARCH_FLAVOR";
export const SEARCH_RECIPE = "SEARCH_RECIPE";
